import { test, expect } from '@playwright/test';
test('onboarding, sample playback, traceable note selection and persisted opt-out', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('checkbox', { name: '今後このメッセージを表示しない', exact: true }).check();
  await page.getByRole('button', { name: 'サンプルを開く' }).click();
  await page.getByRole('button', { name: '次へ', exact: true }).click();
  await page.getByRole('button', { name: 'はじめる', exact: true }).click();
  await expect(page.getByTestId('data-note').first()).toBeVisible();
  await expect(page.getByText('模擬サンプル', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: /Theme.*責務ごと/ }).click();
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Repo.*実装の配置/ }).click();
  await page.screenshot({ path: 'artifacts/arrange-1440.png' });
  await page.getByTestId('data-note').first().click();
  await page.getByRole('button', { name: '調べる', exact: true }).click();
  await expect(page.locator('.monaco-editor')).toBeVisible({ timeout: 20000 });
  await expect(page.getByText('手作業サンプルの説明')).toBeVisible();
  await page.screenshot({ path: 'artifacts/inspect-1440.png' });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.screenshot({ path: 'artifacts/inspect-1280.png' });
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeInViewport();
  await page.getByRole('button', { name: 'Arrangeへ' }).click();
  await page.screenshot({ path: 'artifacts/arrange-1280.png' });
  await page.reload();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect(errors).toEqual([]);
});
